// ------------------------------------------------------------------------------
// DO NOT MODIFY THIS CLASS - AutoGenerated Code
//    Any changes made to this code will be lost the next time this 
//    code is regenerated.
// 
//    Generated at: 13/07/2012 21:36:59
//    DevForce version: 6.1.6.0
//    Template version: 2.1.4
// ------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using IbEm   = IdeaBlade.EntityModel;
using IbCore = IdeaBlade.Core;
using IbVal  = IdeaBlade.Validation;

[module: IbCore.IdeaBladeLicense("M8FavECQoPZAxsmUgA1V57gsKlBl60zxWVKoPIm0Ip2IPxMDyVxZ0Z6mmbhNMZtf")]

namespace ERP.Dao.EntityFramework { 

  #region ErpEntities

  /// <summary>
  /// The domain-specific EntityManager for your domain model.
  /// </summary>
  public partial class ErpEntities : IbEm.EntityManager {

    #region Constructors

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(bool, string, IbEm.EntityServiceOption, string)"/>. </summary>
    public ErpEntities(bool shouldConnect=true, string dataSourceExtension=null, IbEm.EntityServiceOption entityServiceOption=IbEm.EntityServiceOption.UseDefaultService, string compositionContextName=null) : base(shouldConnect, dataSourceExtension, entityServiceOption, compositionContextName) {}

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(IbEm.EntityManagerContext)"/>. </summary>
    public ErpEntities(IbEm.EntityManagerContext entityManagerContext) : base(entityManagerContext) {}

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(IbEm.EntityManager, bool, string, IbEm.EntityServiceOption, string)"/>. </summary>
    public ErpEntities(IbEm.EntityManager entityManager, bool shouldConnect, string dataSourceExtension=null, IbEm.EntityServiceOption entityServiceOption=IbEm.EntityServiceOption.UseDefaultService, string compositionContextName=null) : base(entityManager, shouldConnect, dataSourceExtension, entityServiceOption, compositionContextName) {}

    /// <summary>See <see cref="M:IbEm.EntityManager.#ctor(IbEm.EntityManager, IbEm.EntityManagerContext)"/>. </summary>
    public ErpEntities(IbEm.EntityManager entityManager, IbEm.EntityManagerContext entityManagerContext=null) : base(entityManager, entityManagerContext) {}

    static ErpEntities() {
      IbEm.EntityRelation.InitializeEntityRelations(System.Reflection.Assembly.GetExecutingAssembly());
    }
    #endregion Constructors

    #region EntityQueries

    /// <summary>Gets the <see cref="T:IbEm.EntityQuery"/> associated with the given EntitySet name. </summary>
    public IbEm.EntityQuery<tb_bairro> tb_bairro {
      get { return new IbEm.EntityQuery<tb_bairro>("tb_bairro", this); }
    }

    /// <summary>Gets the <see cref="T:IbEm.EntityQuery"/> associated with the given EntitySet name. </summary>
    public IbEm.EntityQuery<tb_cidade> tb_cidade {
      get { return new IbEm.EntityQuery<tb_cidade>("tb_cidade", this); }
    }

    /// <summary>Gets the <see cref="T:IbEm.EntityQuery"/> associated with the given EntitySet name. </summary>
    public IbEm.EntityQuery<tb_endereco> tb_endereco {
      get { return new IbEm.EntityQuery<tb_endereco>("tb_endereco", this); }
    }

    /// <summary>Gets the <see cref="T:IbEm.EntityQuery"/> associated with the given EntitySet name. </summary>
    public IbEm.EntityQuery<tb_estado> tb_estado {
      get { return new IbEm.EntityQuery<tb_estado>("tb_estado", this); }
    }
    #endregion EntityQueries
  }
  #endregion ErpEntities

  #region tb_bairro class

  /// <summary>The auto-generated tb_bairro class. </summary>
  [DataContract(IsReference=true)]
  [IbEm.DataSourceKeyName(@"ErpEntities")]
  [IbEm.DefaultEntitySetName(@"ErpEntities.tb_bairro")]
  public partial class tb_bairro : IbEm.Entity {

    /// <summary>Returns the property path for the given expression. </summary>
    /// <example>
    /// Usage:
    /// <code>
    ///    var r = Employee.PathFor(e => e.Manager.City); // returns "Manager.City"
    /// </code>
    /// </example>
    public static string PathFor(System.Linq.Expressions.Expression<System.Func<tb_bairro, object>> expr) {
      return IbCore.PropertyPath.For<tb_bairro>(expr);
    }

    #region Data Properties

    /// <summary>Gets or sets the Id. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Id", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_bairro_Id")]
    public int Id {
      get { return PropertyMetadata.Id.GetValue(this); }
      set { PropertyMetadata.Id.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Nome. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Nome", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_bairro_Nome")]
    public string Nome {
      get { return PropertyMetadata.Nome.GetValue(this); }
      set { PropertyMetadata.Nome.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Id_Bairro. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Id_Bairro", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_bairro_Id_Bairro")]
    public int Id_Bairro {
      get { return PropertyMetadata.Id_Bairro.GetValue(this); }
      set { PropertyMetadata.Id_Bairro.SetValue(this, value); }
    }
    #endregion Data Properties

    #region Navigation properties
    #endregion Navigation properties

    #region EntityProperty definitions
    public partial class PropertyMetadata {

      /// Explicit static constructor ensures static fields are initialized.
      static PropertyMetadata() {}

      /// <summary>The Id <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_bairro, int> Id = new IbEm.DataEntityProperty<tb_bairro, int>("Id", false, true, IbEm.ConcurrencyStrategy.None, true, null);

      /// <summary>The Nome <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_bairro, string> Nome = new IbEm.DataEntityProperty<tb_bairro, string>("Nome", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Id_Bairro <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_bairro, int> Id_Bairro = new IbEm.DataEntityProperty<tb_bairro, int>("Id_Bairro", false, true, IbEm.ConcurrencyStrategy.None, false, null);
    }
    #endregion EntityProperty definitions

    #region EntityPropertyNames
    public new partial class EntityPropertyNames : IbEm.Entity.EntityPropertyNames {
      public const String Id = "Id";
      public const String Nome = "Nome";
      public const String Id_Bairro = "Id_Bairro";
    }
    #endregion EntityPropertyNames
  }
  #endregion tb_bairro class

  #region tb_cidade class

  /// <summary>The auto-generated tb_cidade class. </summary>
  [DataContract(IsReference=true)]
  [IbEm.DataSourceKeyName(@"ErpEntities")]
  [IbEm.DefaultEntitySetName(@"ErpEntities.tb_cidade")]
  public partial class tb_cidade : IbEm.Entity {

    /// <summary>Returns the property path for the given expression. </summary>
    /// <example>
    /// Usage:
    /// <code>
    ///    var r = Employee.PathFor(e => e.Manager.City); // returns "Manager.City"
    /// </code>
    /// </example>
    public static string PathFor(System.Linq.Expressions.Expression<System.Func<tb_cidade, object>> expr) {
      return IbCore.PropertyPath.For<tb_cidade>(expr);
    }

    #region Data Properties

    /// <summary>Gets or sets the Id. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Id", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_cidade_Id")]
    public int Id {
      get { return PropertyMetadata.Id.GetValue(this); }
      set { PropertyMetadata.Id.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Nome. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Nome", AutoGenerateField=true)]
    public string Nome {
      get { return PropertyMetadata.Nome.GetValue(this); }
      set { PropertyMetadata.Nome.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Id_Estado. </summary>
    [Key]
    [DataMember]
    [Bindable(false)]
    [Editable(true)]
    [Display(Name="Id_Estado", AutoGenerateField=false)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_cidade_Id_Estado")]
    public int Id_Estado {
      get { return PropertyMetadata.Id_Estado.GetValue(this); }
      set { PropertyMetadata.Id_Estado.SetValue(this, value); }
    }
    #endregion Data Properties

    #region Navigation properties

    /// <summary>Gets or sets the tb_estado. </summary>
    [DataMember]
    [Bindable(false)]
    [Display(Name="tb_estado", AutoGenerateField=false)]
    public tb_estado tb_estado {
      get { return PropertyMetadata.tb_estado.GetValue(this); }
      set { PropertyMetadata.tb_estado.SetValue(this, value); }
    }
    #endregion Navigation properties

    #region EntityProperty definitions
    public partial class PropertyMetadata {

      /// Explicit static constructor ensures static fields are initialized.
      static PropertyMetadata() {}

      /// <summary>The Id <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_cidade, int> Id = new IbEm.DataEntityProperty<tb_cidade, int>("Id", false, true, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Nome <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_cidade, string> Nome = new IbEm.DataEntityProperty<tb_cidade, string>("Nome", true, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Id_Estado <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_cidade, int> Id_Estado = new IbEm.DataEntityProperty<tb_cidade, int>("Id_Estado", false, true, IbEm.ConcurrencyStrategy.None, false, "tb_estado");

      /// <summary>The tb_estado <see cref="T:IbEm.NavigationEntityProperty"/>. </summary>
      public static readonly IbEm.NavigationScalarEntityProperty<tb_cidade, tb_estado> tb_estado = new IbEm.NavigationScalarEntityProperty<tb_cidade, tb_estado>("tb_estado", true, "fk_Tb_Cidade_Tb_Estado1", IbEm.QueryDirection.ToRole2);
    }
    #endregion EntityProperty definitions

    #region EntityPropertyNames
    public new partial class EntityPropertyNames : IbEm.Entity.EntityPropertyNames {
      public const String Id = "Id";
      public const String Nome = "Nome";
      public const String Id_Estado = "Id_Estado";
      public const String tb_estado = "tb_estado";
    }
    #endregion EntityPropertyNames
  }
  #endregion tb_cidade class

  #region tb_endereco class

  /// <summary>The auto-generated tb_endereco class. </summary>
  [DataContract(IsReference=true)]
  [IbEm.DataSourceKeyName(@"ErpEntities")]
  [IbEm.DefaultEntitySetName(@"ErpEntities.tb_endereco")]
  public partial class tb_endereco : IbEm.Entity {

    /// <summary>Returns the property path for the given expression. </summary>
    /// <example>
    /// Usage:
    /// <code>
    ///    var r = Employee.PathFor(e => e.Manager.City); // returns "Manager.City"
    /// </code>
    /// </example>
    public static string PathFor(System.Linq.Expressions.Expression<System.Func<tb_endereco, object>> expr) {
      return IbCore.PropertyPath.For<tb_endereco>(expr);
    }

    #region Data Properties

    /// <summary>Gets or sets the Id. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Id", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_endereco_Id")]
    public int Id {
      get { return PropertyMetadata.Id.GetValue(this); }
      set { PropertyMetadata.Id.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Logradouro. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Logradouro", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_endereco_Logradouro")]
    public string Logradouro {
      get { return PropertyMetadata.Logradouro.GetValue(this); }
      set { PropertyMetadata.Logradouro.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Endereco. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Endereco", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_endereco_Endereco")]
    public string Endereco {
      get { return PropertyMetadata.Endereco.GetValue(this); }
      set { PropertyMetadata.Endereco.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Numero. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Numero", AutoGenerateField=true)]
    public System.Nullable<int> Numero {
      get { return PropertyMetadata.Numero.GetValue(this); }
      set { PropertyMetadata.Numero.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Id_Bairro. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Id_Bairro", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_endereco_Id_Bairro")]
    public int Id_Bairro {
      get { return PropertyMetadata.Id_Bairro.GetValue(this); }
      set { PropertyMetadata.Id_Bairro.SetValue(this, value); }
    }
    #endregion Data Properties

    #region Navigation properties
    #endregion Navigation properties

    #region EntityProperty definitions
    public partial class PropertyMetadata {

      /// Explicit static constructor ensures static fields are initialized.
      static PropertyMetadata() {}

      /// <summary>The Id <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_endereco, int> Id = new IbEm.DataEntityProperty<tb_endereco, int>("Id", false, true, IbEm.ConcurrencyStrategy.None, true, null);

      /// <summary>The Logradouro <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_endereco, string> Logradouro = new IbEm.DataEntityProperty<tb_endereco, string>("Logradouro", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Endereco <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_endereco, string> Endereco = new IbEm.DataEntityProperty<tb_endereco, string>("Endereco", false, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Numero <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_endereco, System.Nullable<int>> Numero = new IbEm.DataEntityProperty<tb_endereco, System.Nullable<int>>("Numero", true, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Id_Bairro <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_endereco, int> Id_Bairro = new IbEm.DataEntityProperty<tb_endereco, int>("Id_Bairro", false, true, IbEm.ConcurrencyStrategy.None, false, null);
    }
    #endregion EntityProperty definitions

    #region EntityPropertyNames
    public new partial class EntityPropertyNames : IbEm.Entity.EntityPropertyNames {
      public const String Id = "Id";
      public const String Logradouro = "Logradouro";
      public const String Endereco = "Endereco";
      public const String Numero = "Numero";
      public const String Id_Bairro = "Id_Bairro";
    }
    #endregion EntityPropertyNames
  }
  #endregion tb_endereco class

  #region tb_estado class

  /// <summary>The auto-generated tb_estado class. </summary>
  [DataContract(IsReference=true)]
  [IbEm.DataSourceKeyName(@"ErpEntities")]
  [IbEm.DefaultEntitySetName(@"ErpEntities.tb_estado")]
  public partial class tb_estado : IbEm.Entity {

    /// <summary>Returns the property path for the given expression. </summary>
    /// <example>
    /// Usage:
    /// <code>
    ///    var r = Employee.PathFor(e => e.Manager.City); // returns "Manager.City"
    /// </code>
    /// </example>
    public static string PathFor(System.Linq.Expressions.Expression<System.Func<tb_estado, object>> expr) {
      return IbCore.PropertyPath.For<tb_estado>(expr);
    }

    #region Data Properties

    /// <summary>Gets or sets the Id. </summary>
    [Key]
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Id", AutoGenerateField=true)]
    [IbVal.RequiredValueVerifier( ErrorMessageResourceName="tb_estado_Id")]
    public int Id {
      get { return PropertyMetadata.Id.GetValue(this); }
      set { PropertyMetadata.Id.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Nome. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Nome", AutoGenerateField=true)]
    public string Nome {
      get { return PropertyMetadata.Nome.GetValue(this); }
      set { PropertyMetadata.Nome.SetValue(this, value); }
    }

    /// <summary>Gets or sets the Uf. </summary>
    [DataMember]
    [Bindable(true, BindingDirection.TwoWay)]
    [Editable(true)]
    [Display(Name="Uf", AutoGenerateField=true)]
    public string Uf {
      get { return PropertyMetadata.Uf.GetValue(this); }
      set { PropertyMetadata.Uf.SetValue(this, value); }
    }
    #endregion Data Properties

    #region Navigation properties

    /// <summary>Gets the tb_cidade. </summary>
    [DataMember]
    [Bindable(false)]
    [Display(Name="tb_cidade", AutoGenerateField=false)]
    public IbEm.RelatedEntityList<tb_cidade> tb_cidade {
      get { return PropertyMetadata.tb_cidade.GetValue(this); }
    }
    #endregion Navigation properties

    #region EntityProperty definitions
    public partial class PropertyMetadata {

      /// Explicit static constructor ensures static fields are initialized.
      static PropertyMetadata() {}

      /// <summary>The Id <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_estado, int> Id = new IbEm.DataEntityProperty<tb_estado, int>("Id", false, true, IbEm.ConcurrencyStrategy.None, true, null);

      /// <summary>The Nome <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_estado, string> Nome = new IbEm.DataEntityProperty<tb_estado, string>("Nome", true, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The Uf <see cref="T:IbEm.DataEntityProperty"/>. </summary>
      public static readonly IbEm.DataEntityProperty<tb_estado, string> Uf = new IbEm.DataEntityProperty<tb_estado, string>("Uf", true, false, IbEm.ConcurrencyStrategy.None, false, null);

      /// <summary>The tb_cidade <see cref="T:IbEm.NavigationEntityProperty"/>. </summary>
      public static readonly IbEm.NavigationListEntityProperty<tb_estado, tb_cidade> tb_cidade = new IbEm.NavigationListEntityProperty<tb_estado, tb_cidade>("tb_cidade", true, "fk_Tb_Cidade_Tb_Estado1", IbEm.QueryDirection.ToRole1);
    }
    #endregion EntityProperty definitions

    #region EntityPropertyNames
    public new partial class EntityPropertyNames : IbEm.Entity.EntityPropertyNames {
      public const String Id = "Id";
      public const String Nome = "Nome";
      public const String Uf = "Uf";
      public const String tb_cidade = "tb_cidade";
    }
    #endregion EntityPropertyNames
  }
  #endregion tb_estado class

  #region EntityRelations

  /// <summary>
  /// A generated class that returns the relations between entities in this model.
  /// </summary>
  [IbCore.IdeaBladeGuid("3a480428-cd54-4d5b-a9a8-7bfab47e3f71", "2.1.4")]
  public partial class EntityRelations : IbEm.IEntityRelations {

    /// Explicit static constructor ensures static fields are initialized.
    static EntityRelations() {}

    /// <summary>
    /// Represents the relationship between 
    /// <see cref="tb_cidade"/> and <see cref="tb_estado"/>.
    /// </summary>
    public static IbEm.EntityRelation fk_Tb_Cidade_Tb_Estado1 = new IbEm.EntityRelation(
      typeof(tb_cidade),
      typeof(tb_estado),
       new IbEm.DataEntityProperty[] { tb_cidade.PropertyMetadata.Id_Estado},
       new IbEm.DataEntityProperty[] { tb_estado.PropertyMetadata.Id},
      IbEm.Multiplicity.Many,
      IbEm.Multiplicity.One,
      IbEm.OnDeleteMode.None,
      IbEm.OnDeleteMode.None,
      "fk_Tb_Cidade_Tb_Estado1");
  }
  #endregion EntityRelations
}
